# Site settings
title: Mr. Fisch
baseurl: "/"
url: "https://shanecurcuru.github.io/mrfisch"
description: >
  Confessions of an Illustrated Educator.
footertitle: Mr.Fisch Speaks
footerdesc: >
  Mr. Fisch is interested in helping your school or educational
  organization keep the fun and fins in your classroom.  Contact
  us for licensing deals, and ask about non-profit discounts!
email: michaelgerb@gmail.com
twitter_username: mrfisch
github_username:  ShaneCurcuru
github_forkurl: https://github.com/ShaneCurcuru/mrfisch
google_customsearch: XYZZY
google_analytics: XYZZY
stripsurl: https://twitter.com/MisterFisch

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
paginate: 6
permalink: none
mdlcolors: indigo-green

# Custom UI settings
default_image: http://mrfisch.com/img/mdl-layout__drawer-avatar.png
sister_sites:
  site1:
    name: Mr. Fisch Store
    link: http://www.cafepress.com/mrfisch
  site3:
    name: House Husband's Cooking Log
    link: http://foodislove1.blogspot.com/

footer_links:
  link1:
    name: About This Site
    link: https://shanecurcuru.github.io/mrfisch/about
  link2:
    name: Impress / Legal / Trademarks
    link: https://shanecurcuru.github.io/mrfisch/colophon

# Build settings
markdown: kramdown
